language: node_js
dist: xenial
node_js:
- '10'
cache:
  yarn: true
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
jobs:
- name: Test
  script: |
    set -ex
    yarn run test
deploy:
  - provider: npm
    email: heremaps-bot@users.noreply.github.com
    skip_cleanup: true
    api_key:
      secure: DTM/lbvlIQHryE9IhIRk114xMJHfSbYadS1Q7fuR85v9HIKuDuJkBNQftuO7TPw+fOggoFW4nOllRT0pSA+tNEFaSuH+4Vu+hqAzWZlQ61P/cfo/9qZDzwmPdja4xIVQX+wBKz1a9NBZeGrpffHuV9vZZdSkD7OzzJiRQGfBe3emAyO7C5mAPLB1G+1mQPLV5kEX2GNmTWujTDYDlPgla2RYWc5u4zW9ZYKO7VQLYrA0fMOFjUbE6xFpDgyEjGWZwlMSVgC3BZUUzS8pV1odeYc4SecDNfrAeLV4ckuYRgdanlLXXaKRDHVm2AjLkGkqY0Wpd0gpQfk9sACy3w7m3Tu0la9XtBHqMphGJFhdilB39E9tGcJnovruOpKPYS6f62/S+GrWK3IgSG4IoGRrS+lNM62PNlPHS4Cr+xStd/0Cu1lbq9IxBUjN9UQrozx65+Wu8OSYseEv2t6EsVFj+7/5G9dO6hiM3Wm2y1K/4TPvpXV3mto2MZg69S1Vsvd3V1GI01Zq0N5WaaOHm16s8ZidrwkKSIyhm8ZQZXn8Ju4I9N40LH/Em1a4dvEvIfq3yjgHFf50tSARZ9iPU8M042AVyHtTDsqk57gYwQMkchDzAtVXJEAywMCBDgTRrd0+5Of/K+l7ZqKaoGYXMfxPQ4X6gSUOjCadechYGVoT1tw=
    on:
      tags: true
      branch: master
